import { config } from 'dotenv';
config();
export const SITE_URL = process.env.SITE_URL;
export const SHAREPOINT_API = process.env.SHAREPOINT_API;
export const PORT = process.env.PORT;
export const CLIENT_ID = process.env.CLIENT_ID;
export const CLIENT_SECRET = process.env.CLIENT_SECRET;
export const TOKEN_SECRET = process.env.TOKEN_SECRET;
export const SENDGRID_API_KEY = process.env.SENDGRID_API_KEY;
export const APP_HOST = process.env.APP_HOST;
export const NO_REPLY_EMAIL = process.env.NO_REPLY_EMAIL;
